name: ci
on:
  push:
    tags:
    branches:
      - master
  pull_request:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: go get
        run: go get
      - name: go fmt
        run: make fmt && git diff --exit-code
      - name: install
        run: sudo apt install libgl1-mesa-dev xorg-dev
      - name: build
        run: make build
      - name: test
        run: make test
